name: 'STAGE CI/CD'

on:
  push:
    branches: [ "main" ]
    paths:
     - "environments/stage/**"
     - ".github/workflows/stage.yml"

    
env:
  TF_VERSION: 1.6.6
  
permissions:
  contents: read

jobs:
  terraform:
    name: 'plan/Apply'
    runs-on: ubuntu-latest
    environment: stage
    env:
          TF_VAR_tenancy_ocid: ${{ secrets.TENANCY_OCID }}
          TF_VAR_user_ocid: ${{ secrets.USER_OCID }}
          TF_VAR_fingerprint: ${{ secrets.FINGERPRINT }}
          TF_VAR_region: ${{ secrets.REGION }}
          TF_VAR_private_key: ${{ secrets.PRIVATE_KEY }}
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with :
           terraform_version: ${{ env.TF_VERSION }}
     
    - name: Setup TFLint
      uses: terraform-linters/setup-tflint@v4

    - name: Run TFLint
      working-directory: environments/stage
      run: tflint || true
    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      working-directory: environments/stage
      run: terraform init
    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      working-directory: environments/stage
      run: terraform fmt

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      working-directory: environments/stage
      run: terraform fmt -check

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      working-directory: environments/stage
      run: terraform plan -var-file="stage.tfvars" -out=tfplan 
    - name: Terraform Init
      run: terraform init
      # On push to "main", build or change infrastructure according to Terraform configuration files
      # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
    - name: Terraform Apply
      working-directory: environments/Dev
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve -var-file="stage.tfvars" -input=false
